name: Build Keycloak theme

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7

      - name: Set up JDK ⚙️
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Setup pnpm ⚙️
        uses: pnpm/action-setup@v6

      - name: Setup Node ⚙️
        uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies ⚙️
        run: pnpm ci

      - name: Build 🔧
        run: pnpm run build-keycloak-theme

      - name: Release 🚀
        uses: softprops/action-gh-release@v3
        with:
          files: dist_keycloak/*
